mvp working
Signed-off-by: Arsh Sharma <arshsharma461@gmail.com>

diff --git a/okteto.yaml b/okteto.yaml
--- a/okteto.yaml
+++ b/okteto.yaml
@@ -6,18 +6,48 @@ deploy:
   image: gcr.io/google.com/cloudsdktool/google-cloud-cli:stable
   commands:
   - name: Create Bucket
-    command: gcloud storage buckets create gs://test-bucket-${OKTETO_NAMESPACE}
+    command: |
+      if ! gcloud storage buckets describe "gs://cloud-cred-demo-${OKTETO_NAMESPACE}" >/dev/null 2>&1;
+      then
+        gcloud storage buckets create "gs://cloud-cred-demo-${OKTETO_NAMESPACE}"
+      else
+        echo "Bucket gs://cloud-cred-demo-${OKTETO_NAMESPACE} already exists. Skipping creation."
+      fi
+
+  - name: Create GCP SA
+    command: |
+      set -e
+      saName="dev-env-${OKTETO_NAMESPACE}"
+      gcpProject="arsh-358508"
+      gcloud iam service-accounts create $saName --project=$gcpProject || echo "Service account already exists, skipping creation."
+
+      gcloud projects add-iam-policy-binding $gcpProject \
+      --member="serviceAccount:$saName@$gcpProject.iam.gserviceaccount.com" \
+      --role="roles/storage.admin"
+
+      gcloud iam service-accounts add-iam-policy-binding $saName@$gcpProject.iam.gserviceaccount.com \
+      --role="roles/iam.workloadIdentityUser" \
+      --member="serviceAccount:$gcpProject.svc.id.goog[${OKTETO_NAMESPACE}/$saName]"
+
   - name: Deploy the app
-    command: helm upgrade --install gcp-app gcp-app --set image=${OKTETO_BUILD_SERVER_IMAGE} --set bucket="test-bucket-${OKTETO_NAMESPACE}"
-
-
-test:
-  gcp:
-    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:stable
-    commands:
-      - gcloud storage ls | grep test-bucket
+    command: helm upgrade --install gcp-app gcp-app --set bucket="cloud-cred-demo-${OKTETO_NAMESPACE}" --set serviceAccountName="dev-env-${OKTETO_NAMESPACE}" --set gcpProject="arsh-358508"
 
 destroy:
   image: gcr.io/google.com/cloudsdktool/google-cloud-cli:stable
   commands:
-    - gcloud storage buckets delete gs://test-bucket-${OKTETO_NAMESPACE}
+  - name: Delete the Bucket Bucket
+    command: |
+      bucket="gs://cloud-cred-demo-${OKTETO_NAMESPACE}"
+      if gcloud storage buckets describe $bucket >/dev/null 2>&1;
+      then
+        gcloud storage buckets update $bucket --uniform-bucket-level-access
+        gcloud storage rm -r $bucket -q
+      else
+        echo "Bucket gs://cloud-cred-demo-${OKTETO_NAMESPACE} does not exist. Skipping deletion."
+      fi
+
+  - name: Delete GCP SA
+    command: |
+      saName="dev-env-${OKTETO_NAMESPACE}"
+      gcpProject="arsh-358508"
+      gcloud iam service-accounts delete $saName@$gcpProject.iam.gserviceaccount.com -q || echo "Service account not found, skipping deletion."
